import Head from 'next/head'

export default function HeaderInfo(){
   return(
      <Head>
        <title>lattelab - good coffee for cool people</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/lattelab.ico" />
      </Head>
   )
}